### ISSUE TITLE
Install Pkg not found

### ISSUE THREAD

**Issue by atthom** [anj1/AlgebraicNumbers.jl#2]
Hello,
Your package is exactly what i'm looking for! However your package could not be found in Pkg

```
julia> using Pkg
julia> Pkg.add("AlgebraicNumber")
ERROR: The following package names could not be resolved:
 * AlgebraicNumber (not found in project, manifest or registry)
Please specify by known `name=uuid`.
```

**Comment by anj1** [comment]
Hi atthom, at the moment there is no tagged release, but I'm actually hoping to change this soon, the package should be released in a few days.

In the mean time, you can install with (press `]` to enter package manager):

pkg> add https://github.com/anj1/AlgebraicNumbers.jl

**Comment by atthom** [comment]
It works like a charm ! 
Many Thanks
